### Create Person 1
### Добавить валидацию полей с помощью hibernate validator (пример: без поля name)
POST /api/v1/persons
Host: localhost:8080
Content-Type: application/json

{
  "name": "Sam",
  "age": 22
}

### Create Person 2
POST /api/v1/persons
Host: localhost:8080
Content-Type: application/json

{
  "name": "Lake",
  "age": 24
}

### Get All Persons +
GET /api/v1/persons
Host: localhost:8080
Accept: application/json

### Get Person By ID +
GET /api/v1/persons/1
Host: localhost:8080
Accept: application/json

### Update Person By ID
### Валидация запросов (поле age)
PUT /api/v1/persons/1
Host: localhost:8080
Content-Type: application/json

{
  "name": "Tom",
  "age": 28
}

### Delete Person By ID +
DELETE /api/v1/persons/1
Host: localhost:8080
